export const FIELD_DEFS = {
  endpointHost: {
    key: "endpointHost",
    label: "地址",
    type: "text",
    placeholder: "example.com / 1.2.3.4",
  },
  endpointPort: {
    key: "endpointPort",
    label: "端口",
    type: "number",
    min: 1,
    max: 65535,
  },
  handshakeHost: {
    key: "handshakeHost",
    label: "SNI / 域名",
    type: "text",
    placeholder: "www.cloudflare.com",
  },
  handshakePort: {
    key: "handshakePort",
    label: "SNI 端口",
    type: "number",
    min: 1,
    max: 65535,
  },
  transportHost: {
    key: "transportHost",
    label: "Host",
    type: "text",
    placeholder: "www.cloudflare.com",
  },
  path: {
    key: "path",
    label: "路径",
    type: "text",
    placeholder: "/",
  },
  serviceName: {
    key: "serviceName",
    label: "Service Name",
    type: "text",
    placeholder: "TunService",
  },
  uuid: {
    key: "uuid",
    label: "UUID",
    type: "text",
  },
  shortId: {
    key: "shortId",
    label: "Short ID",
    type: "text",
    placeholder: "0123456789abcdef",
  },
  method: {
    key: "method",
    label: "方法",
    type: "select",
    options: [
      { value: "2022-blake3-aes-128-gcm", label: "2022-blake3-aes-128-gcm" },
      { value: "2022-blake3-aes-256-gcm", label: "2022-blake3-aes-256-gcm" },
      { value: "2022-blake3-chacha20-poly1305", label: "2022-blake3-chacha20-poly1305" },
      { value: "aes-128-gcm", label: "aes-128-gcm" },
      { value: "aes-192-gcm", label: "aes-192-gcm" },
      { value: "aes-256-gcm", label: "aes-256-gcm" },
      { value: "chacha20-ietf-poly1305", label: "chacha20-ietf-poly1305" },
      { value: "xchacha20-ietf-poly1305", label: "xchacha20-ietf-poly1305" },
    ],
  },
  password: {
    key: "password",
    label: "密码",
    type: "text",
  },
  alterId: {
    key: "alterId",
    label: "Alter ID",
    type: "number",
    min: 0,
    max: 65535,
  },
  certPath: {
    key: "certPath",
    label: "证书路径",
    type: "text",
    placeholder: "/etc/sing-box/fullchain.pem",
  },
  keyPath: {
    key: "keyPath",
    label: "私钥路径",
    type: "text",
    placeholder: "/etc/sing-box/privkey.pem",
  },
  upMbps: {
    key: "upMbps",
    label: "上行 Mbps",
    type: "number",
    min: 0,
  },
  downMbps: {
    key: "downMbps",
    label: "下行 Mbps",
    type: "number",
    min: 0,
  },
  obfsType: {
    key: "obfsType",
    label: "Obfs 类型",
    type: "select",
    options: [
      { value: "", label: "关闭" },
      { value: "salamander", label: "salamander" },
    ],
  },
  obfsPassword: {
    key: "obfsPassword",
    label: "Obfs 密码",
    type: "text",
  },
  congestionControl: {
    key: "congestionControl",
    label: "拥塞控制",
    type: "select",
    options: [
      { value: "cubic", label: "cubic" },
      { value: "new_reno", label: "new_reno" },
      { value: "bbr", label: "bbr" },
    ],
  },
  username: {
    key: "username",
    label: "用户名",
    type: "text",
    placeholder: "nodeget",
  },
};

const VLESS_BASE_FIELDS = ["endpointHost", "endpointPort", "uuid"];
const VLESS_TLS_FIELDS = ["handshakeHost", "certPath", "keyPath"];
const VLESS_TRANS_FIELDS = ["transportHost", "path"];
const VLESS_GRPC_FIELDS = ["serviceName"];
const VMESS_BASE_FIELDS = ["endpointHost", "endpointPort", "uuid", "alterId"];
const TROJAN_BASE_FIELDS = ["endpointHost", "endpointPort", "password"];
const SHARED_TLS_FIELDS = ["handshakeHost", "certPath", "keyPath"];

export const PROTOCOLS = [
  {
    id: "vless-reality",
    label: "VLESS-REALITY",
    family: "vless",
    transport: "tcp",
    tlsMode: "reality",
    secretKind: "uuid-reality",
    fields: [
      "endpointHost",
      "endpointPort",
      "handshakeHost",
      "handshakePort",
      "uuid",
      "shortId",
    ],
    requiredFields: [
      "endpointHost",
      "endpointPort",
      "handshakeHost",
      "handshakePort",
      "uuid",
      "shortId",
    ],
  },
  {
    id: "vless-http2-reality",
    label: "VLESS-HTTP2-REALITY",
    family: "vless",
    transport: "http",
    tlsMode: "reality",
    secretKind: "uuid-reality",
    fields: [
      "endpointHost",
      "endpointPort",
      "handshakeHost",
      "handshakePort",
      "transportHost",
      "path",
      "uuid",
      "shortId",
    ],
    requiredFields: [
      "endpointHost",
      "endpointPort",
      "handshakeHost",
      "handshakePort",
      "transportHost",
      "path",
      "uuid",
      "shortId",
    ],
  },
  {
    id: "vless-ws-tls",
    label: "VLESS-WS-TLS",
    family: "vless",
    transport: "ws",
    tlsMode: "cert",
    secretKind: "uuid",
    fields: [
      "endpointHost",
      "endpointPort",
      ...VLESS_TLS_FIELDS,
      ...VLESS_TRANS_FIELDS,
      "uuid",
    ],
    requiredFields: [
      "endpointHost",
      "endpointPort",
      "handshakeHost",
      "transportHost",
      "path",
      "certPath",
      "keyPath",
      "uuid",
    ],
  },
  {
    id: "vless-h2-tls",
    label: "VLESS-H2-TLS",
    family: "vless",
    transport: "http",
    tlsMode: "cert",
    secretKind: "uuid",
    fields: [
      "endpointHost",
      "endpointPort",
      ...VLESS_TLS_FIELDS,
      ...VLESS_TRANS_FIELDS,
      "uuid",
    ],
    requiredFields: [
      "endpointHost",
      "endpointPort",
      "handshakeHost",
      "transportHost",
      "path",
      "certPath",
      "keyPath",
      "uuid",
    ],
  },
  {
    id: "vless-grpc-tls",
    label: "VLESS-gRPC-TLS",
    family: "vless",
    transport: "grpc",
    tlsMode: "cert",
    secretKind: "uuid",
    fields: [
      "endpointHost",
      "endpointPort",
      ...VLESS_TLS_FIELDS,
      ...VLESS_GRPC_FIELDS,
      "uuid",
    ],
    requiredFields: [
      "endpointHost",
      "endpointPort",
      "handshakeHost",
      "serviceName",
      "certPath",
      "keyPath",
      "uuid",
    ],
  },
  {
    id: "vless-httpupgrade-tls",
    label: "VLESS-HTTPUpgrade-TLS",
    family: "vless",
    transport: "httpupgrade",
    tlsMode: "cert",
    secretKind: "uuid",
    fields: [
      "endpointHost",
      "endpointPort",
      ...VLESS_TLS_FIELDS,
      ...VLESS_TRANS_FIELDS,
      "uuid",
    ],
    requiredFields: [
      "endpointHost",
      "endpointPort",
      "handshakeHost",
      "transportHost",
      "path",
      "certPath",
      "keyPath",
      "uuid",
    ],
  },
  {
    id: "vmess-tcp",
    label: "VMess-TCP",
    family: "vmess",
    transport: "tcp",
    tlsMode: "none",
    secretKind: "uuid",
    fields: VMESS_BASE_FIELDS,
    requiredFields: ["endpointHost", "endpointPort", "uuid"],
  },
  {
    id: "vmess-http",
    label: "VMess-HTTP",
    family: "vmess",
    transport: "http",
    tlsMode: "none",
    secretKind: "uuid",
    fields: [...VMESS_BASE_FIELDS, ...VLESS_TRANS_FIELDS],
    requiredFields: ["endpointHost", "endpointPort", "transportHost", "path", "uuid"],
  },
  {
    id: "vmess-ws",
    label: "VMess-WS",
    family: "vmess",
    transport: "ws",
    tlsMode: "none",
    secretKind: "uuid",
    fields: [...VMESS_BASE_FIELDS, ...VLESS_TRANS_FIELDS],
    requiredFields: ["endpointHost", "endpointPort", "transportHost", "path", "uuid"],
  },
  {
    id: "vmess-ws-tls",
    label: "VMess-WS-TLS",
    family: "vmess",
    transport: "ws",
    tlsMode: "cert",
    secretKind: "uuid",
    fields: [
      ...VMESS_BASE_FIELDS,
      ...SHARED_TLS_FIELDS,
      ...VLESS_TRANS_FIELDS,
    ],
    requiredFields: [
      "endpointHost",
      "endpointPort",
      "handshakeHost",
      "transportHost",
      "path",
      "certPath",
      "keyPath",
      "uuid",
    ],
  },
  {
    id: "vmess-h2-tls",
    label: "VMess-H2-TLS",
    family: "vmess",
    transport: "http",
    tlsMode: "cert",
    secretKind: "uuid",
    fields: [
      ...VMESS_BASE_FIELDS,
      ...SHARED_TLS_FIELDS,
      ...VLESS_TRANS_FIELDS,
    ],
    requiredFields: [
      "endpointHost",
      "endpointPort",
      "handshakeHost",
      "transportHost",
      "path",
      "certPath",
      "keyPath",
      "uuid",
    ],
  },
  {
    id: "vmess-grpc-tls",
    label: "VMess-gRPC-TLS",
    family: "vmess",
    transport: "grpc",
    tlsMode: "cert",
    secretKind: "uuid",
    fields: [
      ...VMESS_BASE_FIELDS,
      ...SHARED_TLS_FIELDS,
      ...VLESS_GRPC_FIELDS,
    ],
    requiredFields: [
      "endpointHost",
      "endpointPort",
      "handshakeHost",
      "serviceName",
      "certPath",
      "keyPath",
      "uuid",
    ],
  },
  {
    id: "vmess-httpupgrade-tls",
    label: "VMess-HTTPUpgrade-TLS",
    family: "vmess",
    transport: "httpupgrade",
    tlsMode: "cert",
    secretKind: "uuid",
    fields: [
      ...VMESS_BASE_FIELDS,
      ...SHARED_TLS_FIELDS,
      ...VLESS_TRANS_FIELDS,
    ],
    requiredFields: [
      "endpointHost",
      "endpointPort",
      "handshakeHost",
      "transportHost",
      "path",
      "certPath",
      "keyPath",
      "uuid",
    ],
  },
  {
    id: "vmess-quic",
    label: "VMess-QUIC",
    family: "vmess",
    transport: "quic",
    tlsMode: "none",
    secretKind: "uuid",
    fields: VMESS_BASE_FIELDS,
    requiredFields: ["endpointHost", "endpointPort", "uuid"],
  },
  {
    id: "trojan-tls",
    label: "Trojan",
    family: "trojan",
    transport: "tcp",
    tlsMode: "cert",
    secretKind: "password",
    fields: [...TROJAN_BASE_FIELDS, ...SHARED_TLS_FIELDS],
    requiredFields: [
      "endpointHost",
      "endpointPort",
      "handshakeHost",
      "certPath",
      "keyPath",
      "password",
    ],
  },
  {
    id: "trojan-ws-tls",
    label: "Trojan-WS-TLS",
    family: "trojan",
    transport: "ws",
    tlsMode: "cert",
    secretKind: "password",
    fields: [...TROJAN_BASE_FIELDS, ...SHARED_TLS_FIELDS, ...VLESS_TRANS_FIELDS],
    requiredFields: [
      "endpointHost",
      "endpointPort",
      "handshakeHost",
      "transportHost",
      "path",
      "certPath",
      "keyPath",
      "password",
    ],
  },
  {
    id: "trojan-h2-tls",
    label: "Trojan-H2-TLS",
    family: "trojan",
    transport: "http",
    tlsMode: "cert",
    secretKind: "password",
    fields: [...TROJAN_BASE_FIELDS, ...SHARED_TLS_FIELDS, ...VLESS_TRANS_FIELDS],
    requiredFields: [
      "endpointHost",
      "endpointPort",
      "handshakeHost",
      "transportHost",
      "path",
      "certPath",
      "keyPath",
      "password",
    ],
  },
  {
    id: "trojan-grpc-tls",
    label: "Trojan-gRPC-TLS",
    family: "trojan",
    transport: "grpc",
    tlsMode: "cert",
    secretKind: "password",
    fields: [...TROJAN_BASE_FIELDS, ...SHARED_TLS_FIELDS, ...VLESS_GRPC_FIELDS],
    requiredFields: [
      "endpointHost",
      "endpointPort",
      "handshakeHost",
      "serviceName",
      "certPath",
      "keyPath",
      "password",
    ],
  },
  {
    id: "trojan-httpupgrade-tls",
    label: "Trojan-HTTPUpgrade-TLS",
    family: "trojan",
    transport: "httpupgrade",
    tlsMode: "cert",
    secretKind: "password",
    fields: [...TROJAN_BASE_FIELDS, ...SHARED_TLS_FIELDS, ...VLESS_TRANS_FIELDS],
    requiredFields: [
      "endpointHost",
      "endpointPort",
      "handshakeHost",
      "transportHost",
      "path",
      "certPath",
      "keyPath",
      "password",
    ],
  },
  {
    id: "shadowsocks",
    label: "Shadowsocks",
    family: "shadowsocks",
    transport: "tcp",
    tlsMode: "none",
    secretKind: "password",
    fields: ["endpointHost", "endpointPort", "method", "password"],
    requiredFields: ["endpointHost", "endpointPort", "method", "password"],
  },
  {
    id: "tuic",
    label: "TUIC",
    family: "tuic",
    transport: "quic",
    tlsMode: "cert",
    secretKind: "uuid-password",
    fields: [
      "endpointHost",
      "endpointPort",
      "handshakeHost",
      "certPath",
      "keyPath",
      "uuid",
      "password",
      "congestionControl",
    ],
    requiredFields: [
      "endpointHost",
      "endpointPort",
      "handshakeHost",
      "certPath",
      "keyPath",
      "uuid",
      "password",
    ],
  },
  {
    id: "anytls",
    label: "AnyTLS",
    family: "anytls",
    transport: "tcp",
    tlsMode: "cert",
    secretKind: "password",
    fields: [
      "endpointHost",
      "endpointPort",
      "handshakeHost",
      "certPath",
      "keyPath",
      "password",
    ],
    requiredFields: [
      "endpointHost",
      "endpointPort",
      "handshakeHost",
      "certPath",
      "keyPath",
      "password",
    ],
  },
  {
    id: "hysteria2",
    label: "Hysteria2",
    family: "hysteria2",
    transport: "quic",
    tlsMode: "cert",
    secretKind: "password",
    fields: [
      "endpointHost",
      "endpointPort",
      "handshakeHost",
      "certPath",
      "keyPath",
      "password",
      "upMbps",
      "downMbps",
      "obfsType",
      "obfsPassword",
    ],
    requiredFields: [
      "endpointHost",
      "endpointPort",
      "handshakeHost",
      "certPath",
      "keyPath",
      "password",
    ],
  },
  {
    id: "socks",
    label: "SOCKS",
    family: "socks",
    transport: "tcp",
    tlsMode: "none",
    secretKind: "socks-userpass",
    fields: ["endpointHost", "endpointPort", "username", "password"],
    requiredFields: ["endpointHost", "endpointPort"],
  },
];

export const PROTOCOL_GROUPS = [
  {
    label: "VLESS",
    protocols: [
      "vless-reality",
      "vless-http2-reality",
      "vless-ws-tls",
      "vless-h2-tls",
      "vless-grpc-tls",
      "vless-httpupgrade-tls",
    ],
  },
  {
    label: "VMess",
    protocols: [
      "vmess-tcp",
      "vmess-http",
      "vmess-ws",
      "vmess-ws-tls",
      "vmess-h2-tls",
      "vmess-grpc-tls",
      "vmess-httpupgrade-tls",
      "vmess-quic",
    ],
  },
  {
    label: "Trojan",
    protocols: [
      "trojan-tls",
      "trojan-ws-tls",
      "trojan-h2-tls",
      "trojan-grpc-tls",
      "trojan-httpupgrade-tls",
    ],
  },
  {
    label: "UDP / 其他",
    protocols: ["shadowsocks", "tuic", "hysteria2", "anytls", "socks"],
  },
];

export function getProtocol(protocolId) {
  return PROTOCOLS.find((protocol) => protocol.id === protocolId) || null;
}

export function getProtocolFields(protocolId) {
  const protocol = getProtocol(protocolId);
  if (!protocol) return [];
  return protocol.fields.map((fieldId) => FIELD_DEFS[fieldId]).filter(Boolean);
}

export function getProtocolRequiredFields(protocolId) {
  const protocol = getProtocol(protocolId);
  if (!protocol) return [];
  return protocol.requiredFields || [];
}

export function getProtocolGroup(protocolId) {
  return PROTOCOL_GROUPS.find((group) => group.protocols.includes(protocolId)) || null;
}
